### ISSUE TITLE
MD export with nullboard-nodejs-agent error

### ISSUE THREAD

**Issue by bonnebulle** [brrd/nbx2md#1]
Hey, thanks, making .md make NB a very best tool !
In general, with "normal" board export/backup nbx2md works amazingly well.

But, when am using [nullboard-nodejs-agent](https://github.com/OfryL/nullboard-nodejs-agent) for backups.
But, with it, when I try to use nbx2md I have an error :
```bash
/usr/lib/node_modules/nbx2md/index.js:8
const contents = list.notes.map(({text, raw}) => (raw ? "### " : "") + text.replace(/(?<!  )\n/gm, "  \
```
I think for sure it is a file structure, certenly nullboard-nodejs-agent dont do an exact same "backup".
Here is not a real issue, more a question for help
Thanks again

**Comment by brrd** [comment]
I'm sorry, I don't know [nullboard-nodejs-agent](https://github.com/OfryL/nullboard-nodejs-agent) and I'm not planning to support it. You will have to ask its maintainer.
